apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-ingress-route-tcp
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ .Values.entryPoint | required "Must supply an entryPoint name that matches your Traefik configuration." }}
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ .Release.Name }}-svc
      port: 2222
