---
# Resource Flavors
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
---
# ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: skaha-cluster-queue
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: [ skaha-workload, canfar-b-workload ]
  queueingStrategy: BestEffortFIFO
  cohort: skaha-cohort
  resourceGroups:
    - coveredResources: ["cpu", "memory", "ephemeral-storage"]
      flavors:
        - name: "default"
          resources:
            - name: "cpu"
              # 40 Nodes * 64 cores = 2560 cores - 1%
              nominalQuota:   2535
              borrowingLimit: 1000
              lendingLimit:   1000
            - name: "memory"
              # 40 Nodes * 241Gi = 9640Gi - 1%
              nominalQuota:   9365Gi
              borrowingLimit: 3750Gi
              lendingLimit:   3750Gi
              # 40 nodes * 2048Gi = 81920Gi
            - name: "ephemeral-storage"
              nominalQuota:   81920Gi
              borrowingLimit: 32768Gi
              lendingLimit:   32768Gi
  preemption:
    reclaimWithinCohort: LowerPriority
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 10000
    withinClusterQueue: LowerPriority
  stopPolicy: None
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: low
value: 10000
description: "Low Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: medium
value: 100000
description: "Medium Priority"
---
# WorkloadPriorityClass
apiVersion: kueue.x-k8s.io/v1beta1
kind: WorkloadPriorityClass
metadata:
  name: high
value: 1000000
description: "High Priority"
