apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: firefly-set-x-forwarded-proto
  namespace: {{ Values.skahaWorkload.namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https