{{- with required "PostgreSQL Database configuration is required." .Values.postgresql }}
{{- if .install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: posix-mapper-postgres-config
  namespace: {{ $.Values.skaha.namespace }}
  labels:
    app: posix-mapper-postgres
data:
  POSTGRES_DB: {{ .auth.database }}
  POSTGRES_USER: {{ .auth.username }}
  POSTGRES_PASSWORD: {{ .auth.password }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: posix-mapper-postgres-init
  namespace: {{ $.Values.skaha.namespace }}
  labels:
    app: posix-mapper-postgres
data:
  init_schema.sql: |
      create schema {{ .auth.schema }};
{{- end }}
{{- end }}